spring:
  application.name: inv-op-back
  datasource:
    url: jdbc:mariadb://localhost:3306/db_inv_op
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql.init.mode: always

server:
  servlet.context-path: /invop
  port: 8081


